FROM ubuntu:18.04
LABEL maintainer="skygoal11111@gmail.com"

RUN apt-get update
RUN apt-get install -y apache2

COPY ./2021_DEV_HTML /var/www/html

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]


